using System.Windows.Media;
using NewUOAM.Positioning.Relay;

namespace NewUOAM.App;

public sealed record PlayerColorOption(string Name, string Hex)
{
    public Brush Brush => PlayerColors.ToBrush(Hex);
}

/// <summary>Player marker/name/chat colors. The picker (MainWindow's PlayerColorPopup) offers a
/// generated grid: every hue in 30° steps at several brightness levels, plus a light grey ramp,
/// plus a custom "#RRGGBB" field. The grid is generated by target *perceived brightness* (relative
/// luminance), not by HSL lightness, on purpose: at the same HSL lightness pure blue looks far
/// darker than yellow, so a lightness-based grid would contain blues that vanish on the dark
/// map/chat background. Every generated color, and every accepted custom color, clears
/// <see cref="MinReadableLuminance"/>. Colors received from other players aren't checked - any
/// valid "RRGGBB" from the wire is rendered as-is.</summary>
public static class PlayerColors
{
    // Declared ABOVE Palette on purpose: static fields initialize in declaration order. An
    // earlier version built each option's brush while initializing Palette, and with this cache
    // declared below it that crashed the app on startup (null lock). Keep it this way.
    private static readonly Dictionary<string, Brush> BrushCache = new();

    /// <summary>Minimum relative luminance (0 = black, 1 = white) for a color to stay readable on
    /// the app's dark backgrounds (#1E1E1E-#2D2D30). Pure blue (0000FF, ~0.07) fails it; the old
    /// default-ish 64B5F6 (~0.42) easily passes.</summary>
    public const double MinReadableLuminance = 0.18;

    public const int PaletteColumns = 12;

    // Perceived-brightness levels, one palette row each (darkest readable → pastel).
    private static readonly double[] LuminanceLevels = [0.2, 0.3, 0.42, 0.56, 0.72];

    public static readonly IReadOnlyList<PlayerColorOption> Palette = BuildPalette();

    private static List<PlayerColorOption> BuildPalette()
    {
        var list = new List<PlayerColorOption>();
        foreach (double target in LuminanceLevels)
        {
            for (int i = 0; i < PaletteColumns; i++)
            {
                string hex = HueAtLuminance(i * 360.0 / PaletteColumns, target);
                list.Add(new PlayerColorOption($"#{hex}", hex));
            }
        }
        // Grey ramp from light-mid grey up to white (all readable), then the protocol's default
        // cyan so it's always one click away even though the generated rows don't hit it exactly.
        for (int i = 0; i < PaletteColumns - 1; i++)
        {
            int v = (int)Math.Round(128 + i * (255 - 128) / (double)(PaletteColumns - 2));
            string hex = $"{v:X2}{v:X2}{v:X2}";
            list.Add(new PlayerColorOption($"#{hex}", hex));
        }
        list.Add(new PlayerColorOption($"#{RelayProtocol.DefaultPlayerColor} (výchozí)", RelayProtocol.DefaultPlayerColor));
        return list;
    }

    /// <summary>Fully saturated color of the given hue whose relative luminance is as close as
    /// possible to <paramref name="targetLuminance"/> - binary search on HSL lightness, which
    /// changes luminance monotonically for a fixed hue/saturation.</summary>
    private static string HueAtLuminance(double hue, double targetLuminance)
    {
        double lo = 0, hi = 1;
        (byte r, byte g, byte b) rgb = (0, 0, 0);
        for (int iter = 0; iter < 30; iter++)
        {
            double mid = (lo + hi) / 2;
            rgb = HslToRgb(hue, 1.0, mid);
            if (RelativeLuminance(rgb.r, rgb.g, rgb.b) < targetLuminance) lo = mid; else hi = mid;
        }
        rgb = HslToRgb(hue, 1.0, hi);
        return $"{rgb.r:X2}{rgb.g:X2}{rgb.b:X2}";
    }

    private static (byte, byte, byte) HslToRgb(double h, double s, double l)
    {
        double c = (1 - Math.Abs(2 * l - 1)) * s;
        double hp = h / 60.0;
        double x = c * (1 - Math.Abs(hp % 2 - 1));
        (double r, double g, double b) = hp switch
        {
            < 1 => (c, x, 0.0),
            < 2 => (x, c, 0.0),
            < 3 => (0.0, c, x),
            < 4 => (0.0, x, c),
            < 5 => (x, 0.0, c),
            _ => (c, 0.0, x),
        };
        double m = l - c / 2;
        return (ToByte(r + m), ToByte(g + m), ToByte(b + m));
        static byte ToByte(double v) => (byte)Math.Clamp(Math.Round(v * 255), 0, 255);
    }

    /// <summary>WCAG relative luminance of an sRGB color.</summary>
    public static double RelativeLuminance(byte r, byte g, byte b)
    {
        static double Lin(byte c)
        {
            double v = c / 255.0;
            return v <= 0.04045 ? v / 12.92 : Math.Pow((v + 0.055) / 1.055, 2.4);
        }
        return 0.2126 * Lin(r) + 0.7152 * Lin(g) + 0.0722 * Lin(b);
    }

    /// <summary>True if a normalized "RRGGBB" color is bright enough to read on the dark UI.</summary>
    public static bool IsReadable(string hex)
    {
        string? n = RelayProtocol.NormalizeColor(hex);
        if (n is null) return false;
        return RelativeLuminance(Convert.ToByte(n[0..2], 16), Convert.ToByte(n[2..4], 16), Convert.ToByte(n[4..6], 16)) >= MinReadableLuminance;
    }

    /// <summary>Frozen, cached brush for an "RRGGBB" color; anything invalid falls back to the
    /// default player color.</summary>
    public static Brush ToBrush(string? hex)
    {
        string normalized = RelayProtocol.NormalizeColor(hex) ?? RelayProtocol.DefaultPlayerColor;
        lock (BrushCache)
        {
            if (BrushCache.TryGetValue(normalized, out var cached)) return cached;
            var brush = new SolidColorBrush(Color.FromRgb(
                Convert.ToByte(normalized[0..2], 16),
                Convert.ToByte(normalized[2..4], 16),
                Convert.ToByte(normalized[4..6], 16)));
            brush.Freeze();
            BrushCache[normalized] = brush;
            return brush;
        }
    }
}
