namespace NewUOAM.App;

/// <summary>
/// Every translated UI text: key, Czech, Slovak, English (see <see cref="Loc"/>). Czech is the
/// app's original wording. A '_' marks a menu access key. {0}, {1} are format arguments.
/// Old UOAM's own English names (Track Player, New Label..., Go to location..., Edit Label,
/// Drop or Pickup Marker, Edit/Delete) are not here: they stay English in every language, as
/// in old UOAM.
/// </summary>
internal static class UiStrings
{
    public static readonly (string Key, string Cs, string Sk, string En)[] All =
    [
        // ---- Menu bar ----
        ("Menu_Map", "_Mapa", "_Mapa", "_Map"),
        ("Menu_Settings", "_Nastavení…", "_Nastavenia…", "_Settings…"),
        ("Menu_NormalView", "N_ormální pohled", "N_ormálny pohľad", "_Normal view"),
        ("Menu_XRayView", "_X-ray pohled", "_X-ray pohľad", "_X-ray view"),
        ("Menu_ShowStatics", "Zo_brazit statiky", "Zo_braziť statiky", "Sh_ow statics"),
        ("Menu_HideStatics", "_Skrýt statiky", "_Skryť statiky", "_Hide statics"),
        ("Menu_Language", "_Jazyk", "_Jazyk", "_Language"),
        ("Menu_CheckUpdates", "_Zkontrolovat aktualizace…", "S_kontrolovať aktualizácie…", "Check for _updates…"),
        ("Menu_Version", "Verze {0}", "Verzia {0}", "Version {0}"),
        ("Menu_Online", "_Online", "_Online", "_Online"),
        ("Menu_Connect", "_Připojit k mapě…", "_Pripojiť k mape…", "_Connect to map…"),
        ("Menu_Client", "_Klient", "_Klient", "_Client"),
        ("Title_Dev", "new UOAM {0} (vývoj)", "new UOAM {0} (vývoj)", "new UOAM {0} (dev)"),
        ("Client_None", "Žádný klient OrionUO neběží", "Nebeží žiadny klient OrionUO", "No OrionUO client is running"),
        ("Client_Auto", "Mapa sama sleduje první spuštěný klient", "Mapa sama sleduje prvý spustený klient", "The map follows the first client started"),
        ("Client_AutoTip",
            "Když sledovaný klient zavřeš, mapa přejde na další běžící. Když žádný neběží, ukazuje 0,0 a čeká na spuštění klienta.",
            "Keď sledovaný klient zavrieš, mapa prejde na ďalší bežiaci. Keď žiadny nebeží, ukazuje 0,0 a čaká na spustenie klienta.",
            "When you close the tracked client, the map switches to the next running one. With none running it shows 0,0 and waits for a client to start."),

        // ---- Map context menu (the rest is old UOAM's English) ----
        ("Ctx_PanicOff", "Vypnout Panic! ({0})", "Vypnúť Panic! ({0})", "Turn off Panic! ({0})"),

        // ---- Over the map ----
        ("Map_SelfArrowTip", "Zpět na mou postavu", "Späť na moju postavu", "Back to my character"),
        ("Map_PanelTip", "Nastavení", "Nastavenia", "Settings"),
        ("Map_UnreadTip", "Nepřečtené zprávy v chatu: {0} (kliknutím otevřeš chat)", "Neprečítané správy v chate: {0} (kliknutím otvoríš chat)", "Unread chat messages: {0} (click to open the chat)"),

        // ---- Side panel (markers) ----
        ("Panel_Markers", "MARKERY", "MARKERY", "MARKERS"),
        ("Panel_Search", "Hledat markery…", "Hľadať markery…", "Search markers…"),
        ("Panel_All", "Vše", "Všetko", "All"),
        ("Panel_AllTip", "Zobrazit všechny kategorie", "Zobraziť všetky kategórie", "Show all categories"),
        ("Panel_None", "Nic", "Nič", "None"),
        ("Panel_NoneTip", "Skrýt všechny kategorie", "Skryť všetky kategórie", "Hide all categories"),
        ("Panel_SharedSectionTip", "Zobrazovat sdílené markery od všech", "Zobrazovať zdieľané markery od všetkých", "Show shared markers from everyone"),
        ("Panel_CategoryTip", "Pravým tlačítkem sdílíš celou kategorii s místností", "Pravým tlačidlom zdieľaš celú kategóriu s miestnosťou", "Right-click to share the whole category with the room"),
        ("Panel_EntryTip", "Klikni pro přesun mapy na marker, pravým tlačítkem ho sdílíš", "Klikni pre presun mapy na marker, pravým tlačidlom ho zdieľaš", "Click to move the map to the marker, right-click to share it"),
        ("Panel_SharedBadge", "sdíleno", "zdieľané", "shared"),
        ("Panel_OwnerTip", "Pravým tlačítkem uložíš všechny jeho markery", "Pravým tlačidlom uložíš všetky jeho markery", "Right-click to save all of their markers"),
        ("Panel_SharedEntryTip", "Klikni pro přesun mapy na marker", "Klikni pre presun mapy na marker", "Click to move the map to the marker"),
        ("Panel_Save", "Uložit", "Uložiť", "Save"),
        ("Panel_SaveTip", "Uložit do Uložené od ostatních (shared_markers.map)", "Uložiť do Uložené od ostatných (shared_markers.map)", "Save to Saved from others (shared_markers.map)"),
        ("Panel_Saved", "uloženo", "uložené", "saved"),
        ("Panel_SectionOwn", "MOJE MARKERY", "MOJE MARKERY", "MY MARKERS"),
        ("Panel_SectionSaved", "ULOŽENÉ OD OSTATNÍCH", "ULOŽENÉ OD OSTATNÝCH", "SAVED FROM OTHERS"),
        ("Panel_SectionShared", "SDÍLENÉ V MÍSTNOSTI", "ZDIEĽANÉ V MIESTNOSTI", "SHARED IN THE ROOM"),
        ("Panel_NothingLoaded",
            "Žádné markery nejsou načtené. Složku s markery nastavíš v Mapa → Nastavení.",
            "Nie sú načítané žiadne markery. Priečinok s markermi nastavíš v Mapa → Nastavenia.",
            "No markers are loaded. Set the markers folder in Map → Settings."),
        ("Panel_NothingFound", "Nic nenalezeno.", "Nič sa nenašlo.", "Nothing found."),
        ("Panel_NoneOnFacet",
            "Na této mapě nejsou žádné markery (dalších {0} je na jiných mapách).",
            "Na tejto mape nie sú žiadne markery (ďalších {0} je na iných mapách).",
            "There are no markers on this map ({0} more are on other maps)."),
        ("Panel_CountOff", "vypnuté", "vypnuté", "off"),
        ("Panel_CountShown", "{0} zobrazeno", "{0} zobrazených", "{0} shown"),

        // ---- Marker context menus ----
        ("Ctx_Share", "Sdílet s místností", "Zdieľať s miestnosťou", "Share with the room"),
        ("Ctx_ShareCategory", "Sdílet kategorii {0} s místností ({1})", "Zdieľať kategóriu {0} s miestnosťou ({1})", "Share category {0} with the room ({1})"),
        ("Ctx_Unshare", "Přestat sdílet", "Prestať zdieľať", "Stop sharing"),
        ("Ctx_UnshareCategory", "Přestat sdílet kategorii {0} ({1})", "Prestať zdieľať kategóriu {0} ({1})", "Stop sharing category {0} ({1})"),
        ("Ctx_UnshareAll", "Přestat sdílet všechny moje markery ({0})", "Prestať zdieľať všetky moje markery ({0})", "Stop sharing all my markers ({0})"),
        ("Ctx_AlreadySaved", "Už uloženo", "Už uložené", "Already saved"),
        ("Ctx_SaveToSaved", "Uložit do Uložené od ostatních", "Uložiť do Uložené od ostatných", "Save to Saved from others"),
        ("Ctx_SaveAllFrom", "Uložit vše od {0}", "Uložiť všetko od {0}", "Save all from {0}"),
        ("Ctx_HideMarker", "Skrýt tento marker", "Skryť tento marker", "Hide this marker"),
        ("Ctx_HideAllFrom", "Skrýt všechny markery od {0}", "Skryť všetky markery od {0}", "Hide all markers from {0}"),
        ("Ctx_MoveToOwn", "Přesunout do Moje markery", "Presunúť do Moje markery", "Move to My markers"),
        ("Ctx_MoveAllToOwn", "Přesunout vše do Moje markery", "Presunúť všetko do Moje markery", "Move all to My markers"),
        ("Ctx_MoveCategoryToOwn", "Přesunout kategorii {0} do Moje markery", "Presunúť kategóriu {0} do Moje markery", "Move category {0} to My markers"),

        // ---- Mapa > Nastavení ----
        ("Dlg_MapSettings", "Nastavení mapy", "Nastavenia mapy", "Map settings"),
        ("Set_MapFiles", "SOUBORY MAPY (.MUL / .UOP)", "SÚBORY MAPY (.MUL / .UOP)", "MAP FILES (.MUL / .UOP)"),
        ("Set_MapFilesHelp",
            "Složka, ve které jsou soubory mapy: map0.mul nebo map0LegacyMUL.uop, statics0.mul, staidx0.mul a radarcol.mul. Obvykle je to hlavní složka klienta Ultima Online.",
            "Priečinok, v ktorom sú súbory mapy: map0.mul alebo map0LegacyMUL.uop, statics0.mul, staidx0.mul a radarcol.mul. Zvyčajne je to hlavný priečinok klienta Ultima Online.",
            "The folder with the map files: map0.mul or map0LegacyMUL.uop, statics0.mul, staidx0.mul and radarcol.mul. Usually the main Ultima Online client folder."),
        ("Set_Browse", "Procházet…", "Prehľadávať…", "Browse…"),
        ("Set_LoadMap", "Načíst mapu", "Načítať mapu", "Load map"),
        ("Set_MarkersHelp",
            "Složka se soubory markerů .map (formát staré UOAM) a .csv. Načtou se všechny tyto soubory přímo v té složce, bez podsložek. Když necháš pole prázdné, použije se složka souborů mapy.",
            "Priečinok so súbormi markerov .map (formát starej UOAM) a .csv. Načítajú sa všetky tieto súbory priamo v tom priečinku, bez podpriečinkov. Keď pole necháš prázdne, použije sa priečinok súborov mapy.",
            "The folder with marker files: .map (old UOAM's format) and .csv. Every such file directly in that folder is loaded, without subfolders. Leave it empty to use the map files folder."),
        ("Set_LoadMarkers", "Načíst markery", "Načítať markery", "Load markers"),
        ("Set_ShowMarkers", "Zobrazit markery", "Zobraziť markery", "Show markers"),
        ("Set_MarkersDirHint", "(složka mapy: {0})", "(priečinok mapy: {0})", "(map folder: {0})"),
        ("Set_MarkersDirHintEmpty", "(složka mapy)", "(priečinok mapy)", "(map folder)"),
        ("Set_BrowseMapTitle", "Vyber složku se soubory mapy (map0.mul / map0LegacyMUL.uop)", "Vyber priečinok so súbormi mapy (map0.mul / map0LegacyMUL.uop)", "Choose the folder with the map files (map0.mul / map0LegacyMUL.uop)"),
        ("Set_BrowseMarkersTitle", "Vyber složku s marker soubory (.map/.csv)", "Vyber priečinok so súbormi markerov (.map/.csv)", "Choose the folder with marker files (.map/.csv)"),
        ("Set_View", "ZOBRAZENÍ", "ZOBRAZENIE", "DISPLAY"),
        ("Set_Rotated", "Pohled: otočený 45°", "Pohľad: otočený o 45°", "View: rotated 45°"),
        ("Set_NorthUp", "Pohled: sever nahoře", "Pohľad: sever hore", "View: north up"),
        ("Set_Coordinates", "Souřadnice", "Súradnice", "Coordinates"),
        ("Set_Compass", "Světové strany", "Svetové strany", "Compass"),
        ("Set_SelfColor", "Barva mé postavy (čtvereček a šipka, vidíš jen ty)", "Farba mojej postavy (štvorček a šípka, vidíš len ty)", "My character's color (square and arrow, only you see it)"),
        ("Set_SelfColorReset", "Výchozí (červená)", "Predvolená (červená)", "Default (red)"),
        ("Set_SelfColorDefault", "#{0} (výchozí)", "#{0} (predvolená)", "#{0} (default)"),
        ("Set_CustomColor", "Vlastní barva (#RRGGBB)", "Vlastná farba (#RRGGBB)", "Custom color (#RRGGBB)"),
        ("Set_Apply", "Použít", "Použiť", "Apply"),
        ("Set_ColorFormatError", "Zadej barvu ve tvaru #RRGGBB, např. #FF8800.", "Zadaj farbu v tvare #RRGGBB, napr. #FF8800.", "Enter a color as #RRGGBB, e.g. #FF8800."),
        ("Set_ColorTooDark",
            "Tahle barva je moc tmavá - na mapě ani v chatu by nebyla čitelná. Zkus světlejší.",
            "Táto farba je príliš tmavá - na mape ani v chate by nebola čitateľná. Skús svetlejšiu.",
            "This color is too dark to read on the map or in the chat. Try a lighter one."),

        // ---- Online > Připojit k mapě ----
        ("Dlg_Connect", "Připojit k mapě", "Pripojiť k mape", "Connect to map"),
        ("On_Address", "Adresa serveru (host:port)", "Adresa servera (host:port)", "Server address (host:port)"),
        ("On_DisplayName", "Zobrazované jméno", "Zobrazované meno", "Display name"),
        ("On_Color", "Barva (jméno a značka na mapě, jméno a text v chatu)", "Farba (meno a značka na mape, meno a text v chate)", "Color (name and marker on the map, name and text in the chat)"),
        ("On_RoomPassword", "Heslo místnosti", "Heslo miestnosti", "Room password"),
        ("On_CreateRoom", "Založit novou místnost…", "Založiť novú miestnosť…", "Create a new room…"),
        ("On_Connect", "Připojit", "Pripojiť", "Connect"),
        ("On_Disconnect", "Odpojit", "Odpojiť", "Disconnect"),
        ("On_Admin", "Admin…", "Admin…", "Admin…"),
        ("On_ChatInGame", "Zobrazovat chat mapy ve hře", "Zobrazovať chat mapy v hre", "Show map chat in the game"),
        ("On_ChatInGameTip",
            "Zprávy z chatu mapy se ukážou v okně Ultimy vlevo dole jako systémové zprávy (vidíš je jen ty). Používá rozhraní UOAssist, které nabízí Orion Assistant - stejně jako stará UOAM.",
            "Správy z chatu mapy sa ukážu v okne Ultimy vľavo dole ako systémové správy (vidíš ich len ty). Používa rozhranie UOAssist, ktoré ponúka Orion Assistant - rovnako ako stará UOAM.",
            "Map chat messages show in the Ultima window at the bottom left as system messages (only you see them). It uses the UOAssist interface that Orion Assistant provides - the same as old UOAM."),
        ("On_PanicSound", "Zvuk při panice spoluhráče", "Zvuk pri panike spoluhráča", "Sound when a room mate panics"),
        ("On_PanicSoundTip",
            "Když někdo v místnosti zapne Panic! (ve hře -panic, nebo v menu mapy), mapa opakovaně pípne, dokud panic trvá.",
            "Keď niekto v miestnosti zapne Panic! (v hre -panic, alebo v menu mapy), mapa opakovane pípa, kým panic trvá.",
            "When someone in the room turns on Panic! (-panic in the game, or the map's menu), the map beeps repeatedly while it lasts."),
        ("On_AutoConnect", "Připojit automaticky při spuštění", "Pripojiť automaticky pri spustení", "Connect automatically at startup"),
        ("On_AutoConnectTip",
            "Po spuštění se mapa sama připojí k místnosti s výše uloženou adresou, jménem a heslem. Chyby se ukážou ve stavovém řádku; když server neodpovídá (třeba hned po zapnutí PC), zkusí to ještě několikrát.",
            "Po spustení sa mapa sama pripojí k miestnosti s vyššie uloženou adresou, menom a heslom. Chyby sa ukážu v stavovom riadku; keď server neodpovedá (napríklad hneď po zapnutí PC), skúsi to ešte niekoľkokrát.",
            "After startup the map connects to the room with the address, name and password saved above. Errors show in the status bar; when the server doesn't answer (e.g. right after the PC starts), it retries a few times."),
        ("On_Unread", "Zobrazovat počet nepřečtených zpráv na mapě", "Zobrazovať počet neprečítaných správ na mape", "Show the number of unread messages on the map"),
        ("On_UnreadTip",
            "Zprávy, které přišly při zavřeném chatu, se počítají vpravo nahoře na mapě. Kliknutím na počítadlo otevřeš chat. Chat si pamatuje všechno od připojení, dokud se neodpojíš.",
            "Správy, ktoré prišli pri zatvorenom chate, sa počítajú vpravo hore na mape. Kliknutím na počítadlo otvoríš chat. Chat si pamätá všetko od pripojenia, kým sa neodpojíš.",
            "Messages that arrive while the chat is closed are counted at the top right of the map. Click the counter to open the chat. The chat keeps everything since you connected, until you disconnect."),
        ("On_CommandsHelp",
            "Ve hře: -c zpráva (chat mapy), -c jméno>zpráva (soukromě), -who (kdo je v místnosti), -t jméno, jméno (tracknutí hráči), -panic, -unpanic. Mezerník v mapě zapne/vypne Panic!",
            "V hre: -c správa (chat mapy), -c meno>správa (súkromne), -who (kto je v miestnosti), -t meno, meno (tracknutí hráči), -panic, -unpanic. Medzerník v mape zapne/vypne Panic!",
            "In the game: -c message (map chat), -c name>message (private), -who (who is in the room), -t name, name (tracked players), -panic, -unpanic. Space on the map turns Panic! on/off."),
        ("On_Tracking", "TRACKING", "TRACKING", "TRACKING"),
        ("On_ShowTrackMap", "Zobrazovat track mapu", "Zobrazovať track mapu", "Show the track map"),
        ("On_ShowTrackMapTip",
            "Druhá malá mapa, která ukáže místo posledního tracku (-t) a jména tracknutých hráčů. Zůstane tam, dokud nepřijde další track nebo ji nezavřeš.",
            "Druhá malá mapa, ktorá ukáže miesto posledného tracku (-t) a mená tracknutých hráčov. Zostane tam, kým nepríde ďalší track alebo ju nezavrieš.",
            "A second small map showing where the last track (-t) was made and the tracked players' names. It stays until the next track or until you close it."),
        ("On_TrackPopup", "Otevřít navrchu, když někdo trackne", "Otvoriť navrchu, keď niekto trackne", "Open on top when someone tracks"),
        ("On_TrackAlways", "Nechat otevřenou pořád", "Nechať otvorenú stále", "Keep it open all the time"),
        ("On_TrackSound", "Zvuk, když někdo trackne", "Zvuk, keď niekto trackne", "Sound when someone tracks"),

        // ---- Chat ----
        ("Chat_InputTip", "Enter odešle zprávu", "Enter odošle správu", "Enter sends the message"),
        ("Chat_PlayersTip", "Hráči v místnosti", "Hráči v miestnosti", "Players in the room"),
        ("Chat_PlayersHeader", "HRÁČI V MÍSTNOSTI", "HRÁČI V MIESTNOSTI", "PLAYERS IN THE ROOM"),
        ("Chat_NotConnected", "Nejsi připojen(a).", "Nie si pripojený/á.", "You're not connected."),
        ("Chat_ClearTip", "Vymazat zprávy (jen u tebe, ostatním zůstanou)", "Vymazať správy (len u teba, ostatným zostanú)", "Clear messages (only here, the others keep them)"),

        // ---- Admin ----
        ("Adm_Title", "new UOAM - Admin místností", "new UOAM - Admin miestností", "new UOAM - Room admin"),
        ("Adm_Header", "ADMIN MÍSTNOSTÍ", "ADMIN MIESTNOSTÍ", "ROOM ADMIN"),
        ("Adm_Address", "Adresa relay serveru (host:port)", "Adresa relay servera (host:port)", "Relay server address (host:port)"),
        ("Adm_Password", "Admin heslo", "Admin heslo", "Admin password"),
        ("Adm_PlayerCreation", "Hráči si můžou zakládat místnosti", "Hráči si môžu zakladať miestnosti", "Players can create rooms"),
        ("Adm_Hint", "Načti seznam (Obnovit). Při spamu zakládání vypni a spam smaž.", "Načítaj zoznam (Obnoviť). Pri spame zakladanie vypni a spam zmaž.", "Load the list (Refresh). If rooms get spammed, turn creation off and delete the spam."),
        ("Adm_Rooms", "MÍSTNOSTI", "MIESTNOSTI", "ROOMS"),
        ("Adm_Refresh", "⟳ Obnovit", "⟳ Obnoviť", "⟳ Refresh"),
        ("Adm_SelectRecent", "Vybrat hráčské za posledních 24 h", "Vybrať hráčske za posledných 24 h", "Select players' rooms from the last 24 h"),
        ("Adm_ColName", "Název", "Názov", "Name"),
        ("Adm_ColBy", "Založil", "Založil", "Created by"),
        ("Adm_ColCreated", "Založeno", "Založená", "Created"),
        ("Adm_ColLastUsed", "Naposledy použita", "Naposledy použitá", "Last used"),
        ("Adm_SourcePlayer", "hráč", "hráč", "player"),
        ("Adm_SourceAdmin", "admin", "admin", "admin"),
        ("Adm_Delete", "Smazat vybrané", "Zmazať vybrané", "Delete selected"),
        ("Adm_MultiHint", "Ctrl / Shift + klik vybere víc místností.", "Ctrl / Shift + klik vyberie viac miestností.", "Ctrl / Shift + click selects several rooms."),
        ("Adm_NewRoom", "Nová místnost s vlastním heslem (admin)", "Nová miestnosť s vlastným heslom (admin)", "New room with your own password (admin)"),
        ("Adm_RoomName", "Jméno místnosti", "Meno miestnosti", "Room name"),
        ("Adm_Create", "Vytvořit místnost", "Vytvoriť miestnosť", "Create room"),

        // ---- Create a room ----
        ("Cr_Title", "Založit místnost", "Založiť miestnosť", "Create a room"),
        ("Cr_Help",
            "Heslo místnosti vygeneruje server. Pošleš ho lidem, se kterými chceš hrát. Místnost, do které se 3 měsíce nikdo nepřipojí, se sama smaže.",
            "Heslo miestnosti vygeneruje server. Pošleš ho ľuďom, s ktorými chceš hrať. Miestnosť, do ktorej sa 3 mesiace nikto nepripojí, sa sama zmaže.",
            "The server generates the room password. Send it to the people you want to play with. A room nobody joins for 3 months deletes itself."),
        ("Cr_Create", "Založit", "Založiť", "Create"),
        ("Cr_Cancel", "Zrušit", "Zrušiť", "Cancel"),
        ("Cr_Copy", "Kopírovat", "Kopírovať", "Copy"),
        ("Cr_Copied", "Zkopírováno", "Skopírované", "Copied"),
        ("Cr_SaveHint",
            "Heslo si ulož nebo pošli spoluhráčům hned. Server ho nikomu nezobrazí, ani adminovi. Kdo heslo zná, může se do místnosti připojit.",
            "Heslo si ulož alebo pošli spoluhráčom hneď. Server ho nikomu nezobrazí, ani adminovi. Kto heslo pozná, môže sa do miestnosti pripojiť.",
            "Save the password or send it to your mates now. The server won't show it to anyone, not even the admin. Anyone who knows it can join the room."),
        ("Cr_Use", "Použít heslo", "Použiť heslo", "Use password"),
        ("Cr_UseTip", "Vyplní heslo v Online > Připojit k mapě. Pak klikni na Připojit.", "Vyplní heslo v Online > Pripojiť k mape. Potom klikni na Pripojiť.", "Fills in the password in Online > Connect to map. Then click Connect."),
        ("Cr_Close", "Zavřít", "Zavrieť", "Close"),
        ("Cr_Done", "Místnost „{0}“ je založená.", "Miestnosť „{0}“ je založená.", "Room “{0}” has been created."),

        // ---- Track map ----
        ("Tr_None", "Zatím žádný track.", "Zatiaľ žiadny track.", "No track yet."),
        ("Tr_CloseTip", "Zavřít track mapu", "Zavrieť track mapu", "Close the track map"),
        ("Tr_JustNow", "právě teď", "práve teraz", "just now"),
        ("Tr_MinutesAgo", "před {0} min", "pred {0} min", "{0} min ago"),
        ("Tr_HoursAgo", "před {0} h", "pred {0} h", "{0} h ago"),
        ("Tr_Players_1", "hráč", "hráč", "player"),
        ("Tr_Players_2", "hráči", "hráči", "players"),
        ("Tr_Players_5", "hráčů", "hráčov", "players"),

        // ---- Update ----
        ("Up_Title", "Aktualizace new UOAM", "Aktualizácia new UOAM", "new UOAM update"),
        ("Up_Header", "Je dostupná nová verze mapy", "Je dostupná nová verzia mapy", "A new version of the map is available"),
        ("Up_Keep",
            "Tvoje markery i nastavení zůstanou, jak jsou. Mapa se po aktualizaci sama znovu spustí.",
            "Tvoje markery aj nastavenia zostanú, ako sú. Mapa sa po aktualizácii sama znova spustí.",
            "Your markers and settings stay as they are. The map restarts itself after the update."),
        ("Up_Version", "Nainstalovaná: {0}   →   nová: {1} ({2}, {3} MB)", "Nainštalovaná: {0}   →   nová: {1} ({2}, {3} MB)", "Installed: {0}   →   new: {1} ({2}, {3} MB)"),
        ("Up_DateFormat", "d. M. yyyy", "d. M. yyyy", "yyyy-MM-dd"),
        ("Up_NoNotes", "(bez popisu změn)", "(bez popisu zmien)", "(no release notes)"),
        ("Up_Update", "Aktualizovat", "Aktualizovať", "Update"),
        ("Up_Later", "Později", "Neskôr", "Later"),
        ("Up_Retry", "Zkusit znovu", "Skúsiť znova", "Try again"),
    ];
}
