using System.Security.Cryptography;
using System.Text.Json;

namespace NewUOAM.Updates;

/// <summary>What one release offers: written by the release tool, signed, read by the app.</summary>
public sealed record UpdateManifest(
    string Product,
    string Version,
    DateTimeOffset PublishedUtc,
    string Notes,
    string PackageUrl,
    string PackageSha256,
    long PackageSize);

public sealed class UpdateException(string message, Exception? inner = null) : Exception(message, inner);

/// <summary>
/// The signed update feed (<c>update.json</c>, an asset of every GitHub release). It's an envelope
/// <c>{"manifest": base64(manifest JSON), "signature": base64(ECDSA P-256/SHA-256 over those
/// bytes)}</c>, so the signature covers the exact bytes the app parses. The manifest names the
/// package zip and its SHA-256, so the zip is covered too. The private key lives only on the
/// publisher's PC (<c>update-signing.key</c>, never in git); the app trusts only
/// <see cref="PublicKey"/>. This is what stops anyone who can tamper with the download (or the
/// GitHub account) from pushing an arbitrary exe to every player.
/// </summary>
public static class UpdateFeed
{
    public const string Product = "NewUOAM";

    /// <summary>GitHub redirects "latest/download" to the newest non-draft, non-prerelease
    /// release's asset of that name, so the app needs no API call and no rate limit applies.</summary>
    public const string DefaultFeedUrl = "https://github.com/Bengur2/new-uoam/releases/latest/download/update.json";

    /// <summary>A package from the default feed must come from this repo's releases.</summary>
    public const string PackageUrlPrefix = "https://github.com/Bengur2/new-uoam/releases/download/";

    /// <summary>SubjectPublicKeyInfo (DER, base64) of the publisher's update-signing key.
    /// Generated by <c>NewUOAM.ReleaseTool keygen</c>. Changing it means every installed copy
    /// stops accepting updates and has to be replaced by hand once - see docs/RELEASE.md.</summary>
    public const string PublicKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEh2vqt2zPckaUb5O2QpXsl64Qd09qifH6zVdfAiVqc2cEBcpOLVN7ioE85aoAdLi62s15auLoBEM2vbuogL3F6A==";

    public const int MaxFeedBytes = 64 * 1024;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
    };

    private sealed record Envelope(string Manifest, string Signature);

    public static string CreateSigned(UpdateManifest manifest, ECDsa privateKey)
    {
        byte[] body = JsonSerializer.SerializeToUtf8Bytes(manifest, JsonOptions);
        byte[] signature = privateKey.SignData(body, HashAlgorithmName.SHA256);
        return JsonSerializer.Serialize(new Envelope(Convert.ToBase64String(body), Convert.ToBase64String(signature)), JsonOptions);
    }

    /// <summary>Parses the envelope and verifies its signature; throws <see cref="UpdateException"/>
    /// for anything that isn't a valid, signed manifest of this product.</summary>
    public static UpdateManifest ParseAndVerify(string feedJson, string publicKeyBase64 = PublicKey)
    {
        Envelope? envelope;
        byte[] body, signature;
        try
        {
            envelope = JsonSerializer.Deserialize<Envelope>(feedJson, JsonOptions);
            if (envelope?.Manifest is null || envelope.Signature is null) throw new UpdateException("Soubor aktualizace nemá očekávaný formát.");
            body = Convert.FromBase64String(envelope.Manifest);
            signature = Convert.FromBase64String(envelope.Signature);
        }
        catch (Exception ex) when (ex is JsonException or FormatException)
        {
            throw new UpdateException("Soubor aktualizace nemá očekávaný formát.", ex);
        }

        using (var key = ECDsa.Create())
        {
            key.ImportSubjectPublicKeyInfo(Convert.FromBase64String(publicKeyBase64), out _);
            if (!key.VerifyData(body, signature, HashAlgorithmName.SHA256))
                throw new UpdateException("Podpis aktualizace nesedí - aktualizace byla odmítnuta.");
        }

        UpdateManifest? manifest;
        try { manifest = JsonSerializer.Deserialize<UpdateManifest>(body, JsonOptions); }
        catch (JsonException ex) { throw new UpdateException("Podepsaný manifest nejde přečíst.", ex); }

        if (manifest is null || manifest.Product != Product || TryParseVersion(manifest.Version) is null
            || string.IsNullOrEmpty(manifest.PackageUrl) || manifest.PackageSha256?.Length != 64 || manifest.PackageSize <= 0)
            throw new UpdateException("Podepsaný manifest je neúplný.");
        return manifest;
    }

    public static string PublicKeyOf(ECDsa key) => Convert.ToBase64String(key.ExportSubjectPublicKeyInfo());

    /// <summary>"1.2.3" (or a System.Version) as major.minor.build, so 1.2.3 and 1.2.3.0 compare equal.</summary>
    public static Version? TryParseVersion(string? text) =>
        Version.TryParse(text, out var v) ? Normalize(v) : null;

    public static Version Normalize(Version v) => new(v.Major, v.Minor, Math.Max(v.Build, 0));

    public static string Sha256OfFile(string path)
    {
        using var stream = File.OpenRead(path);
        return Convert.ToHexString(SHA256.HashData(stream));
    }
}
